# Generated by Django 3.0.5 on 2020-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=64)),
                ('opis', models.TextField()),
                ('rok', models.IntegerField(default=1900)),
                ('plakat', models.ImageField(default=None, upload_to='plakaty')),
            ],
        ),
    ]
